version: '3.6'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - DATABASE_NAME=pencil
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_URL=mongodb:27017
  mongodb:
    image: mongo:latest # Not specified but the latest is > V6 and this is required to support tree structure schemas
    container_name: mongo-container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=pencil
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
